name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hunzg6:$(date +%s)
    - name: Docker Build Tag Publish
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-docker-publish@def3cb9a3ef842b230bf575dc4f5e280ae6a6896
      uses: bitovi/github-actions-docker-publish@v1.0.7
      with:
     # Checkout the repository
        checkout: true # optional, default is true
    # Tag to override default Logic
        image_tag: hunzg6:$(date +%s) # optional, default is 
    # Docker org name.
    org_name: huskynz # optional, default is 
    # Name of the docker repository
    repo_name: hunzg6 # optional, default is 
    # Tag default branch with latest tag instead of branch name.
    use_latest: true # optional, default is true
    # Docker user
    docker_username: peter@husky.nz
    # Docker password
    docker_password: dckr_pat_Ekv5AOy-GGIuWUpHAk6rZ79HU-A
