name: Trigger auto deployment for hunzg6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hunzg6-AutoDeployTrigger-c5c4bb46-53a0-4025-9f02-d7e464e239c8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.HUNZG6_REGISTRY_USERNAME }}
          password: ${{ secrets.HUNZG6_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: huskynz/hunzg6:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HUNZG6_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hunzg6 -g hunz-g6-container --server docker.io --username  ${{ secrets.HUNZG6_REGISTRY_USERNAME }} --password ${{ secrets.HUNZG6_REGISTRY_PASSWORD }}
            az containerapp update -n hunzg6 -g hunz-g6-container --image huskynz/hunzg6:${{ github.sha }}
